#ifndef STREAM_SOLVER_GLOBAL_H
#define STREAM_SOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STREAM_SOLVER_LIBRARY)
#  define STREAM_SOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STREAM_SOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STREAM_SOLVER_GLOBAL_H
